//
//  StandardColors.swift
//  ColorPack
//
//  Created by Shusuke Tokuda on 2016/10/23.
//  Copyright © 2016 tottokotkd. All rights reserved.
//

import Foundation

public struct CSS4Colors {
    public static var aliceBlue: Color {return Color.Hex(red: .xF0, green: .xF8, blue: .xFF)}
    public static var antiqueWhite: Color {return Color.Hex(red: .xFA, green: .xEB, blue: .xD7)}
    public static var aqua: Color {return Color.Hex(red: .x00, green: .xFF, blue: .xFF)}
    public static var aquamarine: Color {return Color.Hex(red: .x7F, green: .xFF, blue: .xD4)}
    public static var azure: Color {return Color.Hex(red: .xF0, green: .xFF, blue: .xFF)}
    public static var beige: Color {return Color.Hex(red: .xF5, green: .xF5, blue: .xDC)}
    public static var bisque: Color {return Color.Hex(red: .xFF, green: .xE4, blue: .xC4)}
    public static var black: Color {return Color.Hex(red: .x00, green: .x00, blue: .x00)}
    public static var blanchedAlmond: Color {return Color.Hex(red: .xFF, green: .xEB, blue: .xCD)}
    public static var blue: Color {return Color.Hex(red: .x00, green: .x00, blue: .xFF)}
    public static var blueViolet: Color {return Color.Hex(red: .x8A, green: .x2B, blue: .xE2)}
    public static var brown: Color {return Color.Hex(red: .xA5, green: .x2A, blue: .x2A)}
    public static var burlyWood: Color {return Color.Hex(red: .xDE, green: .xB8, blue: .x87)}
    public static var cadetBlue: Color {return Color.Hex(red: .x5F, green: .x9E, blue: .xA0)}
    public static var chartreuse: Color {return Color.Hex(red: .x7F, green: .xFF, blue: .x00)}
    public static var chocolate: Color {return Color.Hex(red: .xD2, green: .x69, blue: .x1E)}
    public static var coral: Color {return Color.Hex(red: .xFF, green: .x7F, blue: .x50)}
    public static var cornflowerBlue: Color {return Color.Hex(red: .x64, green: .x95, blue: .xED)}
    public static var cornsilk: Color {return Color.Hex(red: .xFF, green: .xF8, blue: .xDC)}
    public static var crimson: Color {return Color.Hex(red: .xDC, green: .x14, blue: .x3C)}
    public static var cyan: Color {return Color.Hex(red: .x00, green: .xFF, blue: .xFF)}
    public static var darkBlue: Color {return Color.Hex(red: .x00, green: .x00, blue: .x8B)}
    public static var darkCyan: Color {return Color.Hex(red: .x00, green: .x8B, blue: .x8B)}
    public static var darkGoldenRod: Color {return Color.Hex(red: .xB8, green: .x86, blue: .x0B)}
    public static var darkGray: Color {return Color.Hex(red: .xA9, green: .xA9, blue: .xA9)}
    public static var darkGrey: Color {return Color.Hex(red: .xA9, green: .xA9, blue: .xA9)}
    public static var darkGreen: Color {return Color.Hex(red: .x00, green: .x64, blue: .x00)}
    public static var darkKhaki: Color {return Color.Hex(red: .xBD, green: .xB7, blue: .x6B)}
    public static var darkMagenta: Color {return Color.Hex(red: .x8B, green: .x00, blue: .x8B)}
    public static var darkOliveGreen: Color {return Color.Hex(red: .x55, green: .x6B, blue: .x2F)}
    public static var darkOrange: Color {return Color.Hex(red: .xFF, green: .x8C, blue: .x00)}
    public static var darkOrchid: Color {return Color.Hex(red: .x99, green: .x32, blue: .xCC)}
    public static var darkRed: Color {return Color.Hex(red: .x8B, green: .x00, blue: .x00)}
    public static var darkSalmon: Color {return Color.Hex(red: .xE9, green: .x96, blue: .x7A)}
    public static var darkSeaGreen: Color {return Color.Hex(red: .x8F, green: .xBC, blue: .x8F)}
    public static var darkSlateBlue: Color {return Color.Hex(red: .x48, green: .x3D, blue: .x8B)}
    public static var darkSlateGray: Color {return Color.Hex(red: .x2F, green: .x4F, blue: .x4F)}
    public static var darkSlateGrey: Color {return Color.Hex(red: .x2F, green: .x4F, blue: .x4F)}
    public static var darkTurquoise: Color {return Color.Hex(red: .x00, green: .xCE, blue: .xD1)}
    public static var darkViolet: Color {return Color.Hex(red: .x94, green: .x00, blue: .xD3)}
    public static var deepPink: Color {return Color.Hex(red: .xFF, green: .x14, blue: .x93)}
    public static var deepSkyBlue: Color {return Color.Hex(red: .x00, green: .xBF, blue: .xFF)}
    public static var dimGray: Color {return Color.Hex(red: .x69, green: .x69, blue: .x69)}
    public static var dimGrey: Color {return Color.Hex(red: .x69, green: .x69, blue: .x69)}
    public static var dodgerBlue: Color {return Color.Hex(red: .x1E, green: .x90, blue: .xFF)}
    public static var fireBrick: Color {return Color.Hex(red: .xB2, green: .x22, blue: .x22)}
    public static var floralWhite: Color {return Color.Hex(red: .xFF, green: .xFA, blue: .xF0)}
    public static var forestGreen: Color {return Color.Hex(red: .x22, green: .x8B, blue: .x22)}
    public static var fuchsia: Color {return Color.Hex(red: .xFF, green: .x00, blue: .xFF)}
    public static var gainsboro: Color {return Color.Hex(red: .xDC, green: .xDC, blue: .xDC)}
    public static var ghostWhite: Color {return Color.Hex(red: .xF8, green: .xF8, blue: .xFF)}
    public static var gold: Color {return Color.Hex(red: .xFF, green: .xD7, blue: .x00)}
    public static var goldenRod: Color {return Color.Hex(red: .xDA, green: .xA5, blue: .x20)}
    public static var gray: Color {return Color.Hex(red: .x80, green: .x80, blue: .x80)}
    public static var grey: Color {return Color.Hex(red: .x80, green: .x80, blue: .x80)}
    public static var green: Color {return Color.Hex(red: .x00, green: .x80, blue: .x00)}
    public static var greenYellow: Color {return Color.Hex(red: .xAD, green: .xFF, blue: .x2F)}
    public static var honeyDew: Color {return Color.Hex(red: .xF0, green: .xFF, blue: .xF0)}
    public static var hotPink: Color {return Color.Hex(red: .xFF, green: .x69, blue: .xB4)}
    public static var indianRed: Color {return Color.Hex(red: .xCD, green: .x5C, blue: .x5C)}
    public static var indigo: Color {return Color.Hex(red: .x4B, green: .x00, blue: .x82)}
    public static var ivory: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .xF0)}
    public static var khaki: Color {return Color.Hex(red: .xF0, green: .xE6, blue: .x8C)}
    public static var lavender: Color {return Color.Hex(red: .xE6, green: .xE6, blue: .xFA)}
    public static var lavenderBlush: Color {return Color.Hex(red: .xFF, green: .xF0, blue: .xF5)}
    public static var lawnGreen: Color {return Color.Hex(red: .x7C, green: .xFC, blue: .x00)}
    public static var lemonChiffon: Color {return Color.Hex(red: .xFF, green: .xFA, blue: .xCD)}
    public static var lightBlue: Color {return Color.Hex(red: .xAD, green: .xD8, blue: .xE6)}
    public static var lightCoral: Color {return Color.Hex(red: .xF0, green: .x80, blue: .x80)}
    public static var lightCyan: Color {return Color.Hex(red: .xE0, green: .xFF, blue: .xFF)}
    public static var lightGoldenRodYellow: Color {return Color.Hex(red: .xFA, green: .xFA, blue: .xD2)}
    public static var lightGray: Color {return Color.Hex(red: .xD3, green: .xD3, blue: .xD3)}
    public static var lightGrey: Color {return Color.Hex(red: .xD3, green: .xD3, blue: .xD3)}
    public static var lightGreen: Color {return Color.Hex(red: .x90, green: .xEE, blue: .x90)}
    public static var lightPink: Color {return Color.Hex(red: .xFF, green: .xB6, blue: .xC1)}
    public static var lightSalmon: Color {return Color.Hex(red: .xFF, green: .xA0, blue: .x7A)}
    public static var lightSeaGreen: Color {return Color.Hex(red: .x20, green: .xB2, blue: .xAA)}
    public static var lightSkyBlue: Color {return Color.Hex(red: .x87, green: .xCE, blue: .xFA)}
    public static var lightSlateGray: Color {return Color.Hex(red: .x77, green: .x88, blue: .x99)}
    public static var lightSlateGrey: Color {return Color.Hex(red: .x77, green: .x88, blue: .x99)}
    public static var lightSteelBlue: Color {return Color.Hex(red: .xB0, green: .xC4, blue: .xDE)}
    public static var lightYellow: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .xE0)}
    public static var lime: Color {return Color.Hex(red: .x00, green: .xFF, blue: .x00)}
    public static var limeGreen: Color {return Color.Hex(red: .x32, green: .xCD, blue: .x32)}
    public static var linen: Color {return Color.Hex(red: .xFA, green: .xF0, blue: .xE6)}
    public static var magenta: Color {return Color.Hex(red: .xFF, green: .x00, blue: .xFF)}
    public static var maroon: Color {return Color.Hex(red: .x80, green: .x00, blue: .x00)}
    public static var mediumAquaMarine: Color {return Color.Hex(red: .x66, green: .xCD, blue: .xAA)}
    public static var mediumBlue: Color {return Color.Hex(red: .x00, green: .x00, blue: .xCD)}
    public static var mediumOrchid: Color {return Color.Hex(red: .xBA, green: .x55, blue: .xD3)}
    public static var mediumPurple: Color {return Color.Hex(red: .x93, green: .x70, blue: .xDB)}
    public static var mediumSeaGreen: Color {return Color.Hex(red: .x3C, green: .xB3, blue: .x71)}
    public static var mediumSlateBlue: Color {return Color.Hex(red: .x7B, green: .x68, blue: .xEE)}
    public static var mediumSpringGreen: Color {return Color.Hex(red: .x00, green: .xFA, blue: .x9A)}
    public static var mediumTurquoise: Color {return Color.Hex(red: .x48, green: .xD1, blue: .xCC)}
    public static var mediumVioletRed: Color {return Color.Hex(red: .xC7, green: .x15, blue: .x85)}
    public static var midnightBlue: Color {return Color.Hex(red: .x19, green: .x19, blue: .x70)}
    public static var mintCream: Color {return Color.Hex(red: .xF5, green: .xFF, blue: .xFA)}
    public static var mistyRose: Color {return Color.Hex(red: .xFF, green: .xE4, blue: .xE1)}
    public static var moccasin: Color {return Color.Hex(red: .xFF, green: .xE4, blue: .xB5)}
    public static var navajoWhite: Color {return Color.Hex(red: .xFF, green: .xDE, blue: .xAD)}
    public static var navy: Color {return Color.Hex(red: .x00, green: .x00, blue: .x80)}
    public static var oldLace: Color {return Color.Hex(red: .xFD, green: .xF5, blue: .xE6)}
    public static var olive: Color {return Color.Hex(red: .x80, green: .x80, blue: .x00)}
    public static var oliveDrab: Color {return Color.Hex(red: .x6B, green: .x8E, blue: .x23)}
    public static var orange: Color {return Color.Hex(red: .xFF, green: .xA5, blue: .x00)}
    public static var orangeRed: Color {return Color.Hex(red: .xFF, green: .x45, blue: .x00)}
    public static var orchid: Color {return Color.Hex(red: .xDA, green: .x70, blue: .xD6)}
    public static var paleGoldenRod: Color {return Color.Hex(red: .xEE, green: .xE8, blue: .xAA)}
    public static var paleGreen: Color {return Color.Hex(red: .x98, green: .xFB, blue: .x98)}
    public static var paleTurquoise: Color {return Color.Hex(red: .xAF, green: .xEE, blue: .xEE)}
    public static var paleVioletRed: Color {return Color.Hex(red: .xDB, green: .x70, blue: .x93)}
    public static var papayaWhip: Color {return Color.Hex(red: .xFF, green: .xEF, blue: .xD5)}
    public static var peachPuff: Color {return Color.Hex(red: .xFF, green: .xDA, blue: .xB9)}
    public static var peru: Color {return Color.Hex(red: .xCD, green: .x85, blue: .x3F)}
    public static var pink: Color {return Color.Hex(red: .xFF, green: .xC0, blue: .xCB)}
    public static var plum: Color {return Color.Hex(red: .xDD, green: .xA0, blue: .xDD)}
    public static var powderBlue: Color {return Color.Hex(red: .xB0, green: .xE0, blue: .xE6)}
    public static var purple: Color {return Color.Hex(red: .x80, green: .x00, blue: .x80)}
    public static var rebeccaPurple: Color {return Color.Hex(red: .x66, green: .x33, blue: .x99)}
    public static var red: Color {return Color.Hex(red: .xFF, green: .x00, blue: .x00)}
    public static var rosyBrown: Color {return Color.Hex(red: .xBC, green: .x8F, blue: .x8F)}
    public static var royalBlue: Color {return Color.Hex(red: .x41, green: .x69, blue: .xE1)}
    public static var saddleBrown: Color {return Color.Hex(red: .x8B, green: .x45, blue: .x13)}
    public static var salmon: Color {return Color.Hex(red: .xFA, green: .x80, blue: .x72)}
    public static var sandyBrown: Color {return Color.Hex(red: .xF4, green: .xA4, blue: .x60)}
    public static var seaGreen: Color {return Color.Hex(red: .x2E, green: .x8B, blue: .x57)}
    public static var seaShell: Color {return Color.Hex(red: .xFF, green: .xF5, blue: .xEE)}
    public static var sienna: Color {return Color.Hex(red: .xA0, green: .x52, blue: .x2D)}
    public static var silver: Color {return Color.Hex(red: .xC0, green: .xC0, blue: .xC0)}
    public static var skyBlue: Color {return Color.Hex(red: .x87, green: .xCE, blue: .xEB)}
    public static var slateBlue: Color {return Color.Hex(red: .x6A, green: .x5A, blue: .xCD)}
    public static var slateGray: Color {return Color.Hex(red: .x70, green: .x80, blue: .x90)}
    public static var slateGrey: Color {return Color.Hex(red: .x70, green: .x80, blue: .x90)}
    public static var snow: Color {return Color.Hex(red: .xFF, green: .xFA, blue: .xFA)}
    public static var springGreen: Color {return Color.Hex(red: .x00, green: .xFF, blue: .x7F)}
    public static var steelBlue: Color {return Color.Hex(red: .x46, green: .x82, blue: .xB4)}
    public static var tan: Color {return Color.Hex(red: .xD2, green: .xB4, blue: .x8C)}
    public static var teal: Color {return Color.Hex(red: .x00, green: .x80, blue: .x80)}
    public static var thistle: Color {return Color.Hex(red: .xD8, green: .xBF, blue: .xD8)}
    public static var tomato: Color {return Color.Hex(red: .xFF, green: .x63, blue: .x47)}
    public static var turquoise: Color {return Color.Hex(red: .x40, green: .xE0, blue: .xD0)}
    public static var violet: Color {return Color.Hex(red: .xEE, green: .x82, blue: .xEE)}
    public static var wheat: Color {return Color.Hex(red: .xF5, green: .xDE, blue: .xB3)}
    public static var white: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .xFF)}
    public static var whiteSmoke: Color {return Color.Hex(red: .xF5, green: .xF5, blue: .xF5)}
    public static var yellow: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .x00)}
    public static var yellowGreen: Color {return Color.Hex(red: .x9A, green: .xCD, blue: .x32)}
}
