//
//  WebSafeColors.swift
//  ColorPack
//
//  Created by Shusuke Tokuda on 2016/10/23.
//  Copyright © 2016 tottokotkd. All rights reserved.
//

import Foundation

public struct WebSafeColors {
    public static var x000000: Color {return Color.Hex(red: .x00, green: .x00, blue: .x00)}
    public static var x000033: Color {return Color.Hex(red: .x00, green: .x00, blue: .x33)}
    public static var x000066: Color {return Color.Hex(red: .x00, green: .x00, blue: .x66)}
    public static var x000099: Color {return Color.Hex(red: .x00, green: .x00, blue: .x99)}
    public static var x0000CC: Color {return Color.Hex(red: .x00, green: .x00, blue: .xCC)}
    public static var x0000FF: Color {return Color.Hex(red: .x00, green: .x00, blue: .xFF)}
    public static var x003300: Color {return Color.Hex(red: .x00, green: .x33, blue: .x00)}
    public static var x003333: Color {return Color.Hex(red: .x00, green: .x33, blue: .x33)}
    public static var x003366: Color {return Color.Hex(red: .x00, green: .x33, blue: .x66)}
    public static var x003399: Color {return Color.Hex(red: .x00, green: .x33, blue: .x99)}
    public static var x0033CC: Color {return Color.Hex(red: .x00, green: .x33, blue: .xCC)}
    public static var x0033FF: Color {return Color.Hex(red: .x00, green: .x33, blue: .xFF)}
    public static var x006600: Color {return Color.Hex(red: .x00, green: .x66, blue: .x00)}
    public static var x006633: Color {return Color.Hex(red: .x00, green: .x66, blue: .x33)}
    public static var x006666: Color {return Color.Hex(red: .x00, green: .x66, blue: .x66)}
    public static var x006699: Color {return Color.Hex(red: .x00, green: .x66, blue: .x99)}
    public static var x0066CC: Color {return Color.Hex(red: .x00, green: .x66, blue: .xCC)}
    public static var x0066FF: Color {return Color.Hex(red: .x00, green: .x66, blue: .xFF)}
    public static var x009900: Color {return Color.Hex(red: .x00, green: .x99, blue: .x00)}
    public static var x009933: Color {return Color.Hex(red: .x00, green: .x99, blue: .x33)}
    public static var x009966: Color {return Color.Hex(red: .x00, green: .x99, blue: .x66)}
    public static var x009999: Color {return Color.Hex(red: .x00, green: .x99, blue: .x99)}
    public static var x0099CC: Color {return Color.Hex(red: .x00, green: .x99, blue: .xCC)}
    public static var x0099FF: Color {return Color.Hex(red: .x00, green: .x99, blue: .xFF)}
    public static var x00CC00: Color {return Color.Hex(red: .x00, green: .xCC, blue: .x00)}
    public static var x00CC33: Color {return Color.Hex(red: .x00, green: .xCC, blue: .x33)}
    public static var x00CC66: Color {return Color.Hex(red: .x00, green: .xCC, blue: .x66)}
    public static var x00CC99: Color {return Color.Hex(red: .x00, green: .xCC, blue: .x99)}
    public static var x00CCCC: Color {return Color.Hex(red: .x00, green: .xCC, blue: .xCC)}
    public static var x00CCFF: Color {return Color.Hex(red: .x00, green: .xCC, blue: .xFF)}
    public static var x00FF00: Color {return Color.Hex(red: .x00, green: .xFF, blue: .x00)}
    public static var x00FF33: Color {return Color.Hex(red: .x00, green: .xFF, blue: .x33)}
    public static var x00FF66: Color {return Color.Hex(red: .x00, green: .xFF, blue: .x66)}
    public static var x00FF99: Color {return Color.Hex(red: .x00, green: .xFF, blue: .x99)}
    public static var x00FFCC: Color {return Color.Hex(red: .x00, green: .xFF, blue: .xCC)}
    public static var x00FFFF: Color {return Color.Hex(red: .x00, green: .xFF, blue: .xFF)}
    public static var x330000: Color {return Color.Hex(red: .x33, green: .x00, blue: .x00)}
    public static var x330033: Color {return Color.Hex(red: .x33, green: .x00, blue: .x33)}
    public static var x330066: Color {return Color.Hex(red: .x33, green: .x00, blue: .x66)}
    public static var x330099: Color {return Color.Hex(red: .x33, green: .x00, blue: .x99)}
    public static var x3300CC: Color {return Color.Hex(red: .x33, green: .x00, blue: .xCC)}
    public static var x3300FF: Color {return Color.Hex(red: .x33, green: .x00, blue: .xFF)}
    public static var x333300: Color {return Color.Hex(red: .x33, green: .x33, blue: .x00)}
    public static var x333333: Color {return Color.Hex(red: .x33, green: .x33, blue: .x33)}
    public static var x333366: Color {return Color.Hex(red: .x33, green: .x33, blue: .x66)}
    public static var x333399: Color {return Color.Hex(red: .x33, green: .x33, blue: .x99)}
    public static var x3333CC: Color {return Color.Hex(red: .x33, green: .x33, blue: .xCC)}
    public static var x3333FF: Color {return Color.Hex(red: .x33, green: .x33, blue: .xFF)}
    public static var x336600: Color {return Color.Hex(red: .x33, green: .x66, blue: .x00)}
    public static var x336633: Color {return Color.Hex(red: .x33, green: .x66, blue: .x33)}
    public static var x336666: Color {return Color.Hex(red: .x33, green: .x66, blue: .x66)}
    public static var x336699: Color {return Color.Hex(red: .x33, green: .x66, blue: .x99)}
    public static var x3366CC: Color {return Color.Hex(red: .x33, green: .x66, blue: .xCC)}
    public static var x3366FF: Color {return Color.Hex(red: .x33, green: .x66, blue: .xFF)}
    public static var x339900: Color {return Color.Hex(red: .x33, green: .x99, blue: .x00)}
    public static var x339933: Color {return Color.Hex(red: .x33, green: .x99, blue: .x33)}
    public static var x339966: Color {return Color.Hex(red: .x33, green: .x99, blue: .x66)}
    public static var x339999: Color {return Color.Hex(red: .x33, green: .x99, blue: .x99)}
    public static var x3399CC: Color {return Color.Hex(red: .x33, green: .x99, blue: .xCC)}
    public static var x3399FF: Color {return Color.Hex(red: .x33, green: .x99, blue: .xFF)}
    public static var x33CC00: Color {return Color.Hex(red: .x33, green: .xCC, blue: .x00)}
    public static var x33CC33: Color {return Color.Hex(red: .x33, green: .xCC, blue: .x33)}
    public static var x33CC66: Color {return Color.Hex(red: .x33, green: .xCC, blue: .x66)}
    public static var x33CC99: Color {return Color.Hex(red: .x33, green: .xCC, blue: .x99)}
    public static var x33CCCC: Color {return Color.Hex(red: .x33, green: .xCC, blue: .xCC)}
    public static var x33CCFF: Color {return Color.Hex(red: .x33, green: .xCC, blue: .xFF)}
    public static var x33FF00: Color {return Color.Hex(red: .x33, green: .xFF, blue: .x00)}
    public static var x33FF33: Color {return Color.Hex(red: .x33, green: .xFF, blue: .x33)}
    public static var x33FF66: Color {return Color.Hex(red: .x33, green: .xFF, blue: .x66)}
    public static var x33FF99: Color {return Color.Hex(red: .x33, green: .xFF, blue: .x99)}
    public static var x33FFCC: Color {return Color.Hex(red: .x33, green: .xFF, blue: .xCC)}
    public static var x33FFFF: Color {return Color.Hex(red: .x33, green: .xFF, blue: .xFF)}
    public static var x660000: Color {return Color.Hex(red: .x66, green: .x00, blue: .x00)}
    public static var x660033: Color {return Color.Hex(red: .x66, green: .x00, blue: .x33)}
    public static var x660066: Color {return Color.Hex(red: .x66, green: .x00, blue: .x66)}
    public static var x660099: Color {return Color.Hex(red: .x66, green: .x00, blue: .x99)}
    public static var x6600CC: Color {return Color.Hex(red: .x66, green: .x00, blue: .xCC)}
    public static var x6600FF: Color {return Color.Hex(red: .x66, green: .x00, blue: .xFF)}
    public static var x663300: Color {return Color.Hex(red: .x66, green: .x33, blue: .x00)}
    public static var x663333: Color {return Color.Hex(red: .x66, green: .x33, blue: .x33)}
    public static var x663366: Color {return Color.Hex(red: .x66, green: .x33, blue: .x66)}
    public static var x663399: Color {return Color.Hex(red: .x66, green: .x33, blue: .x99)}
    public static var x6633CC: Color {return Color.Hex(red: .x66, green: .x33, blue: .xCC)}
    public static var x6633FF: Color {return Color.Hex(red: .x66, green: .x33, blue: .xFF)}
    public static var x666600: Color {return Color.Hex(red: .x66, green: .x66, blue: .x00)}
    public static var x666633: Color {return Color.Hex(red: .x66, green: .x66, blue: .x33)}
    public static var x666666: Color {return Color.Hex(red: .x66, green: .x66, blue: .x66)}
    public static var x666699: Color {return Color.Hex(red: .x66, green: .x66, blue: .x99)}
    public static var x6666CC: Color {return Color.Hex(red: .x66, green: .x66, blue: .xCC)}
    public static var x6666FF: Color {return Color.Hex(red: .x66, green: .x66, blue: .xFF)}
    public static var x669900: Color {return Color.Hex(red: .x66, green: .x99, blue: .x00)}
    public static var x669933: Color {return Color.Hex(red: .x66, green: .x99, blue: .x33)}
    public static var x669966: Color {return Color.Hex(red: .x66, green: .x99, blue: .x66)}
    public static var x669999: Color {return Color.Hex(red: .x66, green: .x99, blue: .x99)}
    public static var x6699CC: Color {return Color.Hex(red: .x66, green: .x99, blue: .xCC)}
    public static var x6699FF: Color {return Color.Hex(red: .x66, green: .x99, blue: .xFF)}
    public static var x66CC00: Color {return Color.Hex(red: .x66, green: .xCC, blue: .x00)}
    public static var x66CC33: Color {return Color.Hex(red: .x66, green: .xCC, blue: .x33)}
    public static var x66CC66: Color {return Color.Hex(red: .x66, green: .xCC, blue: .x66)}
    public static var x66CC99: Color {return Color.Hex(red: .x66, green: .xCC, blue: .x99)}
    public static var x66CCCC: Color {return Color.Hex(red: .x66, green: .xCC, blue: .xCC)}
    public static var x66CCFF: Color {return Color.Hex(red: .x66, green: .xCC, blue: .xFF)}
    public static var x66FF00: Color {return Color.Hex(red: .x66, green: .xFF, blue: .x00)}
    public static var x66FF33: Color {return Color.Hex(red: .x66, green: .xFF, blue: .x33)}
    public static var x66FF66: Color {return Color.Hex(red: .x66, green: .xFF, blue: .x66)}
    public static var x66FF99: Color {return Color.Hex(red: .x66, green: .xFF, blue: .x99)}
    public static var x66FFCC: Color {return Color.Hex(red: .x66, green: .xFF, blue: .xCC)}
    public static var x66FFFF: Color {return Color.Hex(red: .x66, green: .xFF, blue: .xFF)}
    public static var x990000: Color {return Color.Hex(red: .x99, green: .x00, blue: .x00)}
    public static var x990033: Color {return Color.Hex(red: .x99, green: .x00, blue: .x33)}
    public static var x990066: Color {return Color.Hex(red: .x99, green: .x00, blue: .x66)}
    public static var x990099: Color {return Color.Hex(red: .x99, green: .x00, blue: .x99)}
    public static var x9900CC: Color {return Color.Hex(red: .x99, green: .x00, blue: .xCC)}
    public static var x9900FF: Color {return Color.Hex(red: .x99, green: .x00, blue: .xFF)}
    public static var x993300: Color {return Color.Hex(red: .x99, green: .x33, blue: .x00)}
    public static var x993333: Color {return Color.Hex(red: .x99, green: .x33, blue: .x33)}
    public static var x993366: Color {return Color.Hex(red: .x99, green: .x33, blue: .x66)}
    public static var x993399: Color {return Color.Hex(red: .x99, green: .x33, blue: .x99)}
    public static var x9933CC: Color {return Color.Hex(red: .x99, green: .x33, blue: .xCC)}
    public static var x9933FF: Color {return Color.Hex(red: .x99, green: .x33, blue: .xFF)}
    public static var x996600: Color {return Color.Hex(red: .x99, green: .x66, blue: .x00)}
    public static var x996633: Color {return Color.Hex(red: .x99, green: .x66, blue: .x33)}
    public static var x996666: Color {return Color.Hex(red: .x99, green: .x66, blue: .x66)}
    public static var x996699: Color {return Color.Hex(red: .x99, green: .x66, blue: .x99)}
    public static var x9966CC: Color {return Color.Hex(red: .x99, green: .x66, blue: .xCC)}
    public static var x9966FF: Color {return Color.Hex(red: .x99, green: .x66, blue: .xFF)}
    public static var x999900: Color {return Color.Hex(red: .x99, green: .x99, blue: .x00)}
    public static var x999933: Color {return Color.Hex(red: .x99, green: .x99, blue: .x33)}
    public static var x999966: Color {return Color.Hex(red: .x99, green: .x99, blue: .x66)}
    public static var x999999: Color {return Color.Hex(red: .x99, green: .x99, blue: .x99)}
    public static var x9999CC: Color {return Color.Hex(red: .x99, green: .x99, blue: .xCC)}
    public static var x9999FF: Color {return Color.Hex(red: .x99, green: .x99, blue: .xFF)}
    public static var x99CC00: Color {return Color.Hex(red: .x99, green: .xCC, blue: .x00)}
    public static var x99CC33: Color {return Color.Hex(red: .x99, green: .xCC, blue: .x33)}
    public static var x99CC66: Color {return Color.Hex(red: .x99, green: .xCC, blue: .x66)}
    public static var x99CC99: Color {return Color.Hex(red: .x99, green: .xCC, blue: .x99)}
    public static var x99CCCC: Color {return Color.Hex(red: .x99, green: .xCC, blue: .xCC)}
    public static var x99CCFF: Color {return Color.Hex(red: .x99, green: .xCC, blue: .xFF)}
    public static var x99FF00: Color {return Color.Hex(red: .x99, green: .xFF, blue: .x00)}
    public static var x99FF33: Color {return Color.Hex(red: .x99, green: .xFF, blue: .x33)}
    public static var x99FF66: Color {return Color.Hex(red: .x99, green: .xFF, blue: .x66)}
    public static var x99FF99: Color {return Color.Hex(red: .x99, green: .xFF, blue: .x99)}
    public static var x99FFCC: Color {return Color.Hex(red: .x99, green: .xFF, blue: .xCC)}
    public static var x99FFFF: Color {return Color.Hex(red: .x99, green: .xFF, blue: .xFF)}
    public static var xCC0000: Color {return Color.Hex(red: .xCC, green: .x00, blue: .x00)}
    public static var xCC0033: Color {return Color.Hex(red: .xCC, green: .x00, blue: .x33)}
    public static var xCC0066: Color {return Color.Hex(red: .xCC, green: .x00, blue: .x66)}
    public static var xCC0099: Color {return Color.Hex(red: .xCC, green: .x00, blue: .x99)}
    public static var xCC00CC: Color {return Color.Hex(red: .xCC, green: .x00, blue: .xCC)}
    public static var xCC00FF: Color {return Color.Hex(red: .xCC, green: .x00, blue: .xFF)}
    public static var xCC3300: Color {return Color.Hex(red: .xCC, green: .x33, blue: .x00)}
    public static var xCC3333: Color {return Color.Hex(red: .xCC, green: .x33, blue: .x33)}
    public static var xCC3366: Color {return Color.Hex(red: .xCC, green: .x33, blue: .x66)}
    public static var xCC3399: Color {return Color.Hex(red: .xCC, green: .x33, blue: .x99)}
    public static var xCC33CC: Color {return Color.Hex(red: .xCC, green: .x33, blue: .xCC)}
    public static var xCC33FF: Color {return Color.Hex(red: .xCC, green: .x33, blue: .xFF)}
    public static var xCC6600: Color {return Color.Hex(red: .xCC, green: .x66, blue: .x00)}
    public static var xCC6633: Color {return Color.Hex(red: .xCC, green: .x66, blue: .x33)}
    public static var xCC6666: Color {return Color.Hex(red: .xCC, green: .x66, blue: .x66)}
    public static var xCC6699: Color {return Color.Hex(red: .xCC, green: .x66, blue: .x99)}
    public static var xCC66CC: Color {return Color.Hex(red: .xCC, green: .x66, blue: .xCC)}
    public static var xCC66FF: Color {return Color.Hex(red: .xCC, green: .x66, blue: .xFF)}
    public static var xCC9900: Color {return Color.Hex(red: .xCC, green: .x99, blue: .x00)}
    public static var xCC9933: Color {return Color.Hex(red: .xCC, green: .x99, blue: .x33)}
    public static var xCC9966: Color {return Color.Hex(red: .xCC, green: .x99, blue: .x66)}
    public static var xCC9999: Color {return Color.Hex(red: .xCC, green: .x99, blue: .x99)}
    public static var xCC99CC: Color {return Color.Hex(red: .xCC, green: .x99, blue: .xCC)}
    public static var xCC99FF: Color {return Color.Hex(red: .xCC, green: .x99, blue: .xFF)}
    public static var xCCCC00: Color {return Color.Hex(red: .xCC, green: .xCC, blue: .x00)}
    public static var xCCCC33: Color {return Color.Hex(red: .xCC, green: .xCC, blue: .x33)}
    public static var xCCCC66: Color {return Color.Hex(red: .xCC, green: .xCC, blue: .x66)}
    public static var xCCCC99: Color {return Color.Hex(red: .xCC, green: .xCC, blue: .x99)}
    public static var xCCCCCC: Color {return Color.Hex(red: .xCC, green: .xCC, blue: .xCC)}
    public static var xCCCCFF: Color {return Color.Hex(red: .xCC, green: .xCC, blue: .xFF)}
    public static var xCCFF00: Color {return Color.Hex(red: .xCC, green: .xFF, blue: .x00)}
    public static var xCCFF33: Color {return Color.Hex(red: .xCC, green: .xFF, blue: .x33)}
    public static var xCCFF66: Color {return Color.Hex(red: .xCC, green: .xFF, blue: .x66)}
    public static var xCCFF99: Color {return Color.Hex(red: .xCC, green: .xFF, blue: .x99)}
    public static var xCCFFCC: Color {return Color.Hex(red: .xCC, green: .xFF, blue: .xCC)}
    public static var xCCFFFF: Color {return Color.Hex(red: .xCC, green: .xFF, blue: .xFF)}
    public static var xFF0000: Color {return Color.Hex(red: .xFF, green: .x00, blue: .x00)}
    public static var xFF0033: Color {return Color.Hex(red: .xFF, green: .x00, blue: .x33)}
    public static var xFF0066: Color {return Color.Hex(red: .xFF, green: .x00, blue: .x66)}
    public static var xFF0099: Color {return Color.Hex(red: .xFF, green: .x00, blue: .x99)}
    public static var xFF00CC: Color {return Color.Hex(red: .xFF, green: .x00, blue: .xCC)}
    public static var xFF00FF: Color {return Color.Hex(red: .xFF, green: .x00, blue: .xFF)}
    public static var xFF3300: Color {return Color.Hex(red: .xFF, green: .x33, blue: .x00)}
    public static var xFF3333: Color {return Color.Hex(red: .xFF, green: .x33, blue: .x33)}
    public static var xFF3366: Color {return Color.Hex(red: .xFF, green: .x33, blue: .x66)}
    public static var xFF3399: Color {return Color.Hex(red: .xFF, green: .x33, blue: .x99)}
    public static var xFF33CC: Color {return Color.Hex(red: .xFF, green: .x33, blue: .xCC)}
    public static var xFF33FF: Color {return Color.Hex(red: .xFF, green: .x33, blue: .xFF)}
    public static var xFF6600: Color {return Color.Hex(red: .xFF, green: .x66, blue: .x00)}
    public static var xFF6633: Color {return Color.Hex(red: .xFF, green: .x66, blue: .x33)}
    public static var xFF6666: Color {return Color.Hex(red: .xFF, green: .x66, blue: .x66)}
    public static var xFF6699: Color {return Color.Hex(red: .xFF, green: .x66, blue: .x99)}
    public static var xFF66CC: Color {return Color.Hex(red: .xFF, green: .x66, blue: .xCC)}
    public static var xFF66FF: Color {return Color.Hex(red: .xFF, green: .x66, blue: .xFF)}
    public static var xFF9900: Color {return Color.Hex(red: .xFF, green: .x99, blue: .x00)}
    public static var xFF9933: Color {return Color.Hex(red: .xFF, green: .x99, blue: .x33)}
    public static var xFF9966: Color {return Color.Hex(red: .xFF, green: .x99, blue: .x66)}
    public static var xFF9999: Color {return Color.Hex(red: .xFF, green: .x99, blue: .x99)}
    public static var xFF99CC: Color {return Color.Hex(red: .xFF, green: .x99, blue: .xCC)}
    public static var xFF99FF: Color {return Color.Hex(red: .xFF, green: .x99, blue: .xFF)}
    public static var xFFCC00: Color {return Color.Hex(red: .xFF, green: .xCC, blue: .x00)}
    public static var xFFCC33: Color {return Color.Hex(red: .xFF, green: .xCC, blue: .x33)}
    public static var xFFCC66: Color {return Color.Hex(red: .xFF, green: .xCC, blue: .x66)}
    public static var xFFCC99: Color {return Color.Hex(red: .xFF, green: .xCC, blue: .x99)}
    public static var xFFCCCC: Color {return Color.Hex(red: .xFF, green: .xCC, blue: .xCC)}
    public static var xFFCCFF: Color {return Color.Hex(red: .xFF, green: .xCC, blue: .xFF)}
    public static var xFFFF00: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .x00)}
    public static var xFFFF33: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .x33)}
    public static var xFFFF66: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .x66)}
    public static var xFFFF99: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .x99)}
    public static var xFFFFCC: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .xCC)}
    public static var xFFFFFF: Color {return Color.Hex(red: .xFF, green: .xFF, blue: .xFF)}
}
