//
//  StandardColors.swift
//  ColorPack
//
//  Created by Shusuke Tokuda on 2016/10/23.
//  Copyright © 2016 tottokotkd. All rights reserved.
//

import Foundation

public struct CSS4Colors {
    public static var aliceBlue: ColorProtocol {return Color.hex(red: .xF0, green: .xF8, blue: .xFF)}
    public static var antiqueWhite: ColorProtocol {return Color.hex(red: .xFA, green: .xEB, blue: .xD7)}
    public static var aqua: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .xFF)}
    public static var aquamarine: ColorProtocol {return Color.hex(red: .x7F, green: .xFF, blue: .xD4)}
    public static var azure: ColorProtocol {return Color.hex(red: .xF0, green: .xFF, blue: .xFF)}
    public static var beige: ColorProtocol {return Color.hex(red: .xF5, green: .xF5, blue: .xDC)}
    public static var bisque: ColorProtocol {return Color.hex(red: .xFF, green: .xE4, blue: .xC4)}
    public static var black: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .x00)}
    public static var blanchedAlmond: ColorProtocol {return Color.hex(red: .xFF, green: .xEB, blue: .xCD)}
    public static var blue: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .xFF)}
    public static var blueViolet: ColorProtocol {return Color.hex(red: .x8A, green: .x2B, blue: .xE2)}
    public static var brown: ColorProtocol {return Color.hex(red: .xA5, green: .x2A, blue: .x2A)}
    public static var burlyWood: ColorProtocol {return Color.hex(red: .xDE, green: .xB8, blue: .x87)}
    public static var cadetBlue: ColorProtocol {return Color.hex(red: .x5F, green: .x9E, blue: .xA0)}
    public static var chartreuse: ColorProtocol {return Color.hex(red: .x7F, green: .xFF, blue: .x00)}
    public static var chocolate: ColorProtocol {return Color.hex(red: .xD2, green: .x69, blue: .x1E)}
    public static var coral: ColorProtocol {return Color.hex(red: .xFF, green: .x7F, blue: .x50)}
    public static var cornflowerBlue: ColorProtocol {return Color.hex(red: .x64, green: .x95, blue: .xED)}
    public static var cornsilk: ColorProtocol {return Color.hex(red: .xFF, green: .xF8, blue: .xDC)}
    public static var crimson: ColorProtocol {return Color.hex(red: .xDC, green: .x14, blue: .x3C)}
    public static var cyan: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .xFF)}
    public static var darkBlue: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .x8B)}
    public static var darkCyan: ColorProtocol {return Color.hex(red: .x00, green: .x8B, blue: .x8B)}
    public static var darkGoldenRod: ColorProtocol {return Color.hex(red: .xB8, green: .x86, blue: .x0B)}
    public static var darkGray: ColorProtocol {return Color.hex(red: .xA9, green: .xA9, blue: .xA9)}
    public static var darkGrey: ColorProtocol {return Color.hex(red: .xA9, green: .xA9, blue: .xA9)}
    public static var darkGreen: ColorProtocol {return Color.hex(red: .x00, green: .x64, blue: .x00)}
    public static var darkKhaki: ColorProtocol {return Color.hex(red: .xBD, green: .xB7, blue: .x6B)}
    public static var darkMagenta: ColorProtocol {return Color.hex(red: .x8B, green: .x00, blue: .x8B)}
    public static var darkOliveGreen: ColorProtocol {return Color.hex(red: .x55, green: .x6B, blue: .x2F)}
    public static var darkOrange: ColorProtocol {return Color.hex(red: .xFF, green: .x8C, blue: .x00)}
    public static var darkOrchid: ColorProtocol {return Color.hex(red: .x99, green: .x32, blue: .xCC)}
    public static var darkRed: ColorProtocol {return Color.hex(red: .x8B, green: .x00, blue: .x00)}
    public static var darkSalmon: ColorProtocol {return Color.hex(red: .xE9, green: .x96, blue: .x7A)}
    public static var darkSeaGreen: ColorProtocol {return Color.hex(red: .x8F, green: .xBC, blue: .x8F)}
    public static var darkSlateBlue: ColorProtocol {return Color.hex(red: .x48, green: .x3D, blue: .x8B)}
    public static var darkSlateGray: ColorProtocol {return Color.hex(red: .x2F, green: .x4F, blue: .x4F)}
    public static var darkSlateGrey: ColorProtocol {return Color.hex(red: .x2F, green: .x4F, blue: .x4F)}
    public static var darkTurquoise: ColorProtocol {return Color.hex(red: .x00, green: .xCE, blue: .xD1)}
    public static var darkViolet: ColorProtocol {return Color.hex(red: .x94, green: .x00, blue: .xD3)}
    public static var deepPink: ColorProtocol {return Color.hex(red: .xFF, green: .x14, blue: .x93)}
    public static var deepSkyBlue: ColorProtocol {return Color.hex(red: .x00, green: .xBF, blue: .xFF)}
    public static var dimGray: ColorProtocol {return Color.hex(red: .x69, green: .x69, blue: .x69)}
    public static var dimGrey: ColorProtocol {return Color.hex(red: .x69, green: .x69, blue: .x69)}
    public static var dodgerBlue: ColorProtocol {return Color.hex(red: .x1E, green: .x90, blue: .xFF)}
    public static var fireBrick: ColorProtocol {return Color.hex(red: .xB2, green: .x22, blue: .x22)}
    public static var floralWhite: ColorProtocol {return Color.hex(red: .xFF, green: .xFA, blue: .xF0)}
    public static var forestGreen: ColorProtocol {return Color.hex(red: .x22, green: .x8B, blue: .x22)}
    public static var fuchsia: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .xFF)}
    public static var gainsboro: ColorProtocol {return Color.hex(red: .xDC, green: .xDC, blue: .xDC)}
    public static var ghostWhite: ColorProtocol {return Color.hex(red: .xF8, green: .xF8, blue: .xFF)}
    public static var gold: ColorProtocol {return Color.hex(red: .xFF, green: .xD7, blue: .x00)}
    public static var goldenRod: ColorProtocol {return Color.hex(red: .xDA, green: .xA5, blue: .x20)}
    public static var gray: ColorProtocol {return Color.hex(red: .x80, green: .x80, blue: .x80)}
    public static var grey: ColorProtocol {return Color.hex(red: .x80, green: .x80, blue: .x80)}
    public static var green: ColorProtocol {return Color.hex(red: .x00, green: .x80, blue: .x00)}
    public static var greenYellow: ColorProtocol {return Color.hex(red: .xAD, green: .xFF, blue: .x2F)}
    public static var honeyDew: ColorProtocol {return Color.hex(red: .xF0, green: .xFF, blue: .xF0)}
    public static var hotPink: ColorProtocol {return Color.hex(red: .xFF, green: .x69, blue: .xB4)}
    public static var indianRed: ColorProtocol {return Color.hex(red: .xCD, green: .x5C, blue: .x5C)}
    public static var indigo: ColorProtocol {return Color.hex(red: .x4B, green: .x00, blue: .x82)}
    public static var ivory: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .xF0)}
    public static var khaki: ColorProtocol {return Color.hex(red: .xF0, green: .xE6, blue: .x8C)}
    public static var lavender: ColorProtocol {return Color.hex(red: .xE6, green: .xE6, blue: .xFA)}
    public static var lavenderBlush: ColorProtocol {return Color.hex(red: .xFF, green: .xF0, blue: .xF5)}
    public static var lawnGreen: ColorProtocol {return Color.hex(red: .x7C, green: .xFC, blue: .x00)}
    public static var lemonChiffon: ColorProtocol {return Color.hex(red: .xFF, green: .xFA, blue: .xCD)}
    public static var lightBlue: ColorProtocol {return Color.hex(red: .xAD, green: .xD8, blue: .xE6)}
    public static var lightCoral: ColorProtocol {return Color.hex(red: .xF0, green: .x80, blue: .x80)}
    public static var lightCyan: ColorProtocol {return Color.hex(red: .xE0, green: .xFF, blue: .xFF)}
    public static var lightGoldenRodYellow: ColorProtocol {return Color.hex(red: .xFA, green: .xFA, blue: .xD2)}
    public static var lightGray: ColorProtocol {return Color.hex(red: .xD3, green: .xD3, blue: .xD3)}
    public static var lightGrey: ColorProtocol {return Color.hex(red: .xD3, green: .xD3, blue: .xD3)}
    public static var lightGreen: ColorProtocol {return Color.hex(red: .x90, green: .xEE, blue: .x90)}
    public static var lightPink: ColorProtocol {return Color.hex(red: .xFF, green: .xB6, blue: .xC1)}
    public static var lightSalmon: ColorProtocol {return Color.hex(red: .xFF, green: .xA0, blue: .x7A)}
    public static var lightSeaGreen: ColorProtocol {return Color.hex(red: .x20, green: .xB2, blue: .xAA)}
    public static var lightSkyBlue: ColorProtocol {return Color.hex(red: .x87, green: .xCE, blue: .xFA)}
    public static var lightSlateGray: ColorProtocol {return Color.hex(red: .x77, green: .x88, blue: .x99)}
    public static var lightSlateGrey: ColorProtocol {return Color.hex(red: .x77, green: .x88, blue: .x99)}
    public static var lightSteelBlue: ColorProtocol {return Color.hex(red: .xB0, green: .xC4, blue: .xDE)}
    public static var lightYellow: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .xE0)}
    public static var lime: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .x00)}
    public static var limeGreen: ColorProtocol {return Color.hex(red: .x32, green: .xCD, blue: .x32)}
    public static var linen: ColorProtocol {return Color.hex(red: .xFA, green: .xF0, blue: .xE6)}
    public static var magenta: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .xFF)}
    public static var maroon: ColorProtocol {return Color.hex(red: .x80, green: .x00, blue: .x00)}
    public static var mediumAquaMarine: ColorProtocol {return Color.hex(red: .x66, green: .xCD, blue: .xAA)}
    public static var mediumBlue: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .xCD)}
    public static var mediumOrchid: ColorProtocol {return Color.hex(red: .xBA, green: .x55, blue: .xD3)}
    public static var mediumPurple: ColorProtocol {return Color.hex(red: .x93, green: .x70, blue: .xDB)}
    public static var mediumSeaGreen: ColorProtocol {return Color.hex(red: .x3C, green: .xB3, blue: .x71)}
    public static var mediumSlateBlue: ColorProtocol {return Color.hex(red: .x7B, green: .x68, blue: .xEE)}
    public static var mediumSpringGreen: ColorProtocol {return Color.hex(red: .x00, green: .xFA, blue: .x9A)}
    public static var mediumTurquoise: ColorProtocol {return Color.hex(red: .x48, green: .xD1, blue: .xCC)}
    public static var mediumVioletRed: ColorProtocol {return Color.hex(red: .xC7, green: .x15, blue: .x85)}
    public static var midnightBlue: ColorProtocol {return Color.hex(red: .x19, green: .x19, blue: .x70)}
    public static var mintCream: ColorProtocol {return Color.hex(red: .xF5, green: .xFF, blue: .xFA)}
    public static var mistyRose: ColorProtocol {return Color.hex(red: .xFF, green: .xE4, blue: .xE1)}
    public static var moccasin: ColorProtocol {return Color.hex(red: .xFF, green: .xE4, blue: .xB5)}
    public static var navajoWhite: ColorProtocol {return Color.hex(red: .xFF, green: .xDE, blue: .xAD)}
    public static var navy: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .x80)}
    public static var oldLace: ColorProtocol {return Color.hex(red: .xFD, green: .xF5, blue: .xE6)}
    public static var olive: ColorProtocol {return Color.hex(red: .x80, green: .x80, blue: .x00)}
    public static var oliveDrab: ColorProtocol {return Color.hex(red: .x6B, green: .x8E, blue: .x23)}
    public static var orange: ColorProtocol {return Color.hex(red: .xFF, green: .xA5, blue: .x00)}
    public static var orangeRed: ColorProtocol {return Color.hex(red: .xFF, green: .x45, blue: .x00)}
    public static var orchid: ColorProtocol {return Color.hex(red: .xDA, green: .x70, blue: .xD6)}
    public static var paleGoldenRod: ColorProtocol {return Color.hex(red: .xEE, green: .xE8, blue: .xAA)}
    public static var paleGreen: ColorProtocol {return Color.hex(red: .x98, green: .xFB, blue: .x98)}
    public static var paleTurquoise: ColorProtocol {return Color.hex(red: .xAF, green: .xEE, blue: .xEE)}
    public static var paleVioletRed: ColorProtocol {return Color.hex(red: .xDB, green: .x70, blue: .x93)}
    public static var papayaWhip: ColorProtocol {return Color.hex(red: .xFF, green: .xEF, blue: .xD5)}
    public static var peachPuff: ColorProtocol {return Color.hex(red: .xFF, green: .xDA, blue: .xB9)}
    public static var peru: ColorProtocol {return Color.hex(red: .xCD, green: .x85, blue: .x3F)}
    public static var pink: ColorProtocol {return Color.hex(red: .xFF, green: .xC0, blue: .xCB)}
    public static var plum: ColorProtocol {return Color.hex(red: .xDD, green: .xA0, blue: .xDD)}
    public static var powderBlue: ColorProtocol {return Color.hex(red: .xB0, green: .xE0, blue: .xE6)}
    public static var purple: ColorProtocol {return Color.hex(red: .x80, green: .x00, blue: .x80)}
    public static var rebeccaPurple: ColorProtocol {return Color.hex(red: .x66, green: .x33, blue: .x99)}
    public static var red: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .x00)}
    public static var rosyBrown: ColorProtocol {return Color.hex(red: .xBC, green: .x8F, blue: .x8F)}
    public static var royalBlue: ColorProtocol {return Color.hex(red: .x41, green: .x69, blue: .xE1)}
    public static var saddleBrown: ColorProtocol {return Color.hex(red: .x8B, green: .x45, blue: .x13)}
    public static var salmon: ColorProtocol {return Color.hex(red: .xFA, green: .x80, blue: .x72)}
    public static var sandyBrown: ColorProtocol {return Color.hex(red: .xF4, green: .xA4, blue: .x60)}
    public static var seaGreen: ColorProtocol {return Color.hex(red: .x2E, green: .x8B, blue: .x57)}
    public static var seaShell: ColorProtocol {return Color.hex(red: .xFF, green: .xF5, blue: .xEE)}
    public static var sienna: ColorProtocol {return Color.hex(red: .xA0, green: .x52, blue: .x2D)}
    public static var silver: ColorProtocol {return Color.hex(red: .xC0, green: .xC0, blue: .xC0)}
    public static var skyBlue: ColorProtocol {return Color.hex(red: .x87, green: .xCE, blue: .xEB)}
    public static var slateBlue: ColorProtocol {return Color.hex(red: .x6A, green: .x5A, blue: .xCD)}
    public static var slateGray: ColorProtocol {return Color.hex(red: .x70, green: .x80, blue: .x90)}
    public static var slateGrey: ColorProtocol {return Color.hex(red: .x70, green: .x80, blue: .x90)}
    public static var snow: ColorProtocol {return Color.hex(red: .xFF, green: .xFA, blue: .xFA)}
    public static var springGreen: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .x7F)}
    public static var steelBlue: ColorProtocol {return Color.hex(red: .x46, green: .x82, blue: .xB4)}
    public static var tan: ColorProtocol {return Color.hex(red: .xD2, green: .xB4, blue: .x8C)}
    public static var teal: ColorProtocol {return Color.hex(red: .x00, green: .x80, blue: .x80)}
    public static var thistle: ColorProtocol {return Color.hex(red: .xD8, green: .xBF, blue: .xD8)}
    public static var tomato: ColorProtocol {return Color.hex(red: .xFF, green: .x63, blue: .x47)}
    public static var turquoise: ColorProtocol {return Color.hex(red: .x40, green: .xE0, blue: .xD0)}
    public static var violet: ColorProtocol {return Color.hex(red: .xEE, green: .x82, blue: .xEE)}
    public static var wheat: ColorProtocol {return Color.hex(red: .xF5, green: .xDE, blue: .xB3)}
    public static var white: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .xFF)}
    public static var whiteSmoke: ColorProtocol {return Color.hex(red: .xF5, green: .xF5, blue: .xF5)}
    public static var yellow: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .x00)}
    public static var yellowGreen: ColorProtocol {return Color.hex(red: .x9A, green: .xCD, blue: .x32)}
}
