//
//  WebSafeColors.swift
//  ColorPack
//
//  Created by Shusuke Tokuda on 2016/10/23.
//  Copyright © 2016 tottokotkd. All rights reserved.
//

import Foundation

public struct WebSafeColors {
    public static var x000000: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .x00)}
    public static var x000033: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .x33)}
    public static var x000066: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .x66)}
    public static var x000099: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .x99)}
    public static var x0000CC: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .xCC)}
    public static var x0000FF: ColorProtocol {return Color.hex(red: .x00, green: .x00, blue: .xFF)}
    public static var x003300: ColorProtocol {return Color.hex(red: .x00, green: .x33, blue: .x00)}
    public static var x003333: ColorProtocol {return Color.hex(red: .x00, green: .x33, blue: .x33)}
    public static var x003366: ColorProtocol {return Color.hex(red: .x00, green: .x33, blue: .x66)}
    public static var x003399: ColorProtocol {return Color.hex(red: .x00, green: .x33, blue: .x99)}
    public static var x0033CC: ColorProtocol {return Color.hex(red: .x00, green: .x33, blue: .xCC)}
    public static var x0033FF: ColorProtocol {return Color.hex(red: .x00, green: .x33, blue: .xFF)}
    public static var x006600: ColorProtocol {return Color.hex(red: .x00, green: .x66, blue: .x00)}
    public static var x006633: ColorProtocol {return Color.hex(red: .x00, green: .x66, blue: .x33)}
    public static var x006666: ColorProtocol {return Color.hex(red: .x00, green: .x66, blue: .x66)}
    public static var x006699: ColorProtocol {return Color.hex(red: .x00, green: .x66, blue: .x99)}
    public static var x0066CC: ColorProtocol {return Color.hex(red: .x00, green: .x66, blue: .xCC)}
    public static var x0066FF: ColorProtocol {return Color.hex(red: .x00, green: .x66, blue: .xFF)}
    public static var x009900: ColorProtocol {return Color.hex(red: .x00, green: .x99, blue: .x00)}
    public static var x009933: ColorProtocol {return Color.hex(red: .x00, green: .x99, blue: .x33)}
    public static var x009966: ColorProtocol {return Color.hex(red: .x00, green: .x99, blue: .x66)}
    public static var x009999: ColorProtocol {return Color.hex(red: .x00, green: .x99, blue: .x99)}
    public static var x0099CC: ColorProtocol {return Color.hex(red: .x00, green: .x99, blue: .xCC)}
    public static var x0099FF: ColorProtocol {return Color.hex(red: .x00, green: .x99, blue: .xFF)}
    public static var x00CC00: ColorProtocol {return Color.hex(red: .x00, green: .xCC, blue: .x00)}
    public static var x00CC33: ColorProtocol {return Color.hex(red: .x00, green: .xCC, blue: .x33)}
    public static var x00CC66: ColorProtocol {return Color.hex(red: .x00, green: .xCC, blue: .x66)}
    public static var x00CC99: ColorProtocol {return Color.hex(red: .x00, green: .xCC, blue: .x99)}
    public static var x00CCCC: ColorProtocol {return Color.hex(red: .x00, green: .xCC, blue: .xCC)}
    public static var x00CCFF: ColorProtocol {return Color.hex(red: .x00, green: .xCC, blue: .xFF)}
    public static var x00FF00: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .x00)}
    public static var x00FF33: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .x33)}
    public static var x00FF66: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .x66)}
    public static var x00FF99: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .x99)}
    public static var x00FFCC: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .xCC)}
    public static var x00FFFF: ColorProtocol {return Color.hex(red: .x00, green: .xFF, blue: .xFF)}
    public static var x330000: ColorProtocol {return Color.hex(red: .x33, green: .x00, blue: .x00)}
    public static var x330033: ColorProtocol {return Color.hex(red: .x33, green: .x00, blue: .x33)}
    public static var x330066: ColorProtocol {return Color.hex(red: .x33, green: .x00, blue: .x66)}
    public static var x330099: ColorProtocol {return Color.hex(red: .x33, green: .x00, blue: .x99)}
    public static var x3300CC: ColorProtocol {return Color.hex(red: .x33, green: .x00, blue: .xCC)}
    public static var x3300FF: ColorProtocol {return Color.hex(red: .x33, green: .x00, blue: .xFF)}
    public static var x333300: ColorProtocol {return Color.hex(red: .x33, green: .x33, blue: .x00)}
    public static var x333333: ColorProtocol {return Color.hex(red: .x33, green: .x33, blue: .x33)}
    public static var x333366: ColorProtocol {return Color.hex(red: .x33, green: .x33, blue: .x66)}
    public static var x333399: ColorProtocol {return Color.hex(red: .x33, green: .x33, blue: .x99)}
    public static var x3333CC: ColorProtocol {return Color.hex(red: .x33, green: .x33, blue: .xCC)}
    public static var x3333FF: ColorProtocol {return Color.hex(red: .x33, green: .x33, blue: .xFF)}
    public static var x336600: ColorProtocol {return Color.hex(red: .x33, green: .x66, blue: .x00)}
    public static var x336633: ColorProtocol {return Color.hex(red: .x33, green: .x66, blue: .x33)}
    public static var x336666: ColorProtocol {return Color.hex(red: .x33, green: .x66, blue: .x66)}
    public static var x336699: ColorProtocol {return Color.hex(red: .x33, green: .x66, blue: .x99)}
    public static var x3366CC: ColorProtocol {return Color.hex(red: .x33, green: .x66, blue: .xCC)}
    public static var x3366FF: ColorProtocol {return Color.hex(red: .x33, green: .x66, blue: .xFF)}
    public static var x339900: ColorProtocol {return Color.hex(red: .x33, green: .x99, blue: .x00)}
    public static var x339933: ColorProtocol {return Color.hex(red: .x33, green: .x99, blue: .x33)}
    public static var x339966: ColorProtocol {return Color.hex(red: .x33, green: .x99, blue: .x66)}
    public static var x339999: ColorProtocol {return Color.hex(red: .x33, green: .x99, blue: .x99)}
    public static var x3399CC: ColorProtocol {return Color.hex(red: .x33, green: .x99, blue: .xCC)}
    public static var x3399FF: ColorProtocol {return Color.hex(red: .x33, green: .x99, blue: .xFF)}
    public static var x33CC00: ColorProtocol {return Color.hex(red: .x33, green: .xCC, blue: .x00)}
    public static var x33CC33: ColorProtocol {return Color.hex(red: .x33, green: .xCC, blue: .x33)}
    public static var x33CC66: ColorProtocol {return Color.hex(red: .x33, green: .xCC, blue: .x66)}
    public static var x33CC99: ColorProtocol {return Color.hex(red: .x33, green: .xCC, blue: .x99)}
    public static var x33CCCC: ColorProtocol {return Color.hex(red: .x33, green: .xCC, blue: .xCC)}
    public static var x33CCFF: ColorProtocol {return Color.hex(red: .x33, green: .xCC, blue: .xFF)}
    public static var x33FF00: ColorProtocol {return Color.hex(red: .x33, green: .xFF, blue: .x00)}
    public static var x33FF33: ColorProtocol {return Color.hex(red: .x33, green: .xFF, blue: .x33)}
    public static var x33FF66: ColorProtocol {return Color.hex(red: .x33, green: .xFF, blue: .x66)}
    public static var x33FF99: ColorProtocol {return Color.hex(red: .x33, green: .xFF, blue: .x99)}
    public static var x33FFCC: ColorProtocol {return Color.hex(red: .x33, green: .xFF, blue: .xCC)}
    public static var x33FFFF: ColorProtocol {return Color.hex(red: .x33, green: .xFF, blue: .xFF)}
    public static var x660000: ColorProtocol {return Color.hex(red: .x66, green: .x00, blue: .x00)}
    public static var x660033: ColorProtocol {return Color.hex(red: .x66, green: .x00, blue: .x33)}
    public static var x660066: ColorProtocol {return Color.hex(red: .x66, green: .x00, blue: .x66)}
    public static var x660099: ColorProtocol {return Color.hex(red: .x66, green: .x00, blue: .x99)}
    public static var x6600CC: ColorProtocol {return Color.hex(red: .x66, green: .x00, blue: .xCC)}
    public static var x6600FF: ColorProtocol {return Color.hex(red: .x66, green: .x00, blue: .xFF)}
    public static var x663300: ColorProtocol {return Color.hex(red: .x66, green: .x33, blue: .x00)}
    public static var x663333: ColorProtocol {return Color.hex(red: .x66, green: .x33, blue: .x33)}
    public static var x663366: ColorProtocol {return Color.hex(red: .x66, green: .x33, blue: .x66)}
    public static var x663399: ColorProtocol {return Color.hex(red: .x66, green: .x33, blue: .x99)}
    public static var x6633CC: ColorProtocol {return Color.hex(red: .x66, green: .x33, blue: .xCC)}
    public static var x6633FF: ColorProtocol {return Color.hex(red: .x66, green: .x33, blue: .xFF)}
    public static var x666600: ColorProtocol {return Color.hex(red: .x66, green: .x66, blue: .x00)}
    public static var x666633: ColorProtocol {return Color.hex(red: .x66, green: .x66, blue: .x33)}
    public static var x666666: ColorProtocol {return Color.hex(red: .x66, green: .x66, blue: .x66)}
    public static var x666699: ColorProtocol {return Color.hex(red: .x66, green: .x66, blue: .x99)}
    public static var x6666CC: ColorProtocol {return Color.hex(red: .x66, green: .x66, blue: .xCC)}
    public static var x6666FF: ColorProtocol {return Color.hex(red: .x66, green: .x66, blue: .xFF)}
    public static var x669900: ColorProtocol {return Color.hex(red: .x66, green: .x99, blue: .x00)}
    public static var x669933: ColorProtocol {return Color.hex(red: .x66, green: .x99, blue: .x33)}
    public static var x669966: ColorProtocol {return Color.hex(red: .x66, green: .x99, blue: .x66)}
    public static var x669999: ColorProtocol {return Color.hex(red: .x66, green: .x99, blue: .x99)}
    public static var x6699CC: ColorProtocol {return Color.hex(red: .x66, green: .x99, blue: .xCC)}
    public static var x6699FF: ColorProtocol {return Color.hex(red: .x66, green: .x99, blue: .xFF)}
    public static var x66CC00: ColorProtocol {return Color.hex(red: .x66, green: .xCC, blue: .x00)}
    public static var x66CC33: ColorProtocol {return Color.hex(red: .x66, green: .xCC, blue: .x33)}
    public static var x66CC66: ColorProtocol {return Color.hex(red: .x66, green: .xCC, blue: .x66)}
    public static var x66CC99: ColorProtocol {return Color.hex(red: .x66, green: .xCC, blue: .x99)}
    public static var x66CCCC: ColorProtocol {return Color.hex(red: .x66, green: .xCC, blue: .xCC)}
    public static var x66CCFF: ColorProtocol {return Color.hex(red: .x66, green: .xCC, blue: .xFF)}
    public static var x66FF00: ColorProtocol {return Color.hex(red: .x66, green: .xFF, blue: .x00)}
    public static var x66FF33: ColorProtocol {return Color.hex(red: .x66, green: .xFF, blue: .x33)}
    public static var x66FF66: ColorProtocol {return Color.hex(red: .x66, green: .xFF, blue: .x66)}
    public static var x66FF99: ColorProtocol {return Color.hex(red: .x66, green: .xFF, blue: .x99)}
    public static var x66FFCC: ColorProtocol {return Color.hex(red: .x66, green: .xFF, blue: .xCC)}
    public static var x66FFFF: ColorProtocol {return Color.hex(red: .x66, green: .xFF, blue: .xFF)}
    public static var x990000: ColorProtocol {return Color.hex(red: .x99, green: .x00, blue: .x00)}
    public static var x990033: ColorProtocol {return Color.hex(red: .x99, green: .x00, blue: .x33)}
    public static var x990066: ColorProtocol {return Color.hex(red: .x99, green: .x00, blue: .x66)}
    public static var x990099: ColorProtocol {return Color.hex(red: .x99, green: .x00, blue: .x99)}
    public static var x9900CC: ColorProtocol {return Color.hex(red: .x99, green: .x00, blue: .xCC)}
    public static var x9900FF: ColorProtocol {return Color.hex(red: .x99, green: .x00, blue: .xFF)}
    public static var x993300: ColorProtocol {return Color.hex(red: .x99, green: .x33, blue: .x00)}
    public static var x993333: ColorProtocol {return Color.hex(red: .x99, green: .x33, blue: .x33)}
    public static var x993366: ColorProtocol {return Color.hex(red: .x99, green: .x33, blue: .x66)}
    public static var x993399: ColorProtocol {return Color.hex(red: .x99, green: .x33, blue: .x99)}
    public static var x9933CC: ColorProtocol {return Color.hex(red: .x99, green: .x33, blue: .xCC)}
    public static var x9933FF: ColorProtocol {return Color.hex(red: .x99, green: .x33, blue: .xFF)}
    public static var x996600: ColorProtocol {return Color.hex(red: .x99, green: .x66, blue: .x00)}
    public static var x996633: ColorProtocol {return Color.hex(red: .x99, green: .x66, blue: .x33)}
    public static var x996666: ColorProtocol {return Color.hex(red: .x99, green: .x66, blue: .x66)}
    public static var x996699: ColorProtocol {return Color.hex(red: .x99, green: .x66, blue: .x99)}
    public static var x9966CC: ColorProtocol {return Color.hex(red: .x99, green: .x66, blue: .xCC)}
    public static var x9966FF: ColorProtocol {return Color.hex(red: .x99, green: .x66, blue: .xFF)}
    public static var x999900: ColorProtocol {return Color.hex(red: .x99, green: .x99, blue: .x00)}
    public static var x999933: ColorProtocol {return Color.hex(red: .x99, green: .x99, blue: .x33)}
    public static var x999966: ColorProtocol {return Color.hex(red: .x99, green: .x99, blue: .x66)}
    public static var x999999: ColorProtocol {return Color.hex(red: .x99, green: .x99, blue: .x99)}
    public static var x9999CC: ColorProtocol {return Color.hex(red: .x99, green: .x99, blue: .xCC)}
    public static var x9999FF: ColorProtocol {return Color.hex(red: .x99, green: .x99, blue: .xFF)}
    public static var x99CC00: ColorProtocol {return Color.hex(red: .x99, green: .xCC, blue: .x00)}
    public static var x99CC33: ColorProtocol {return Color.hex(red: .x99, green: .xCC, blue: .x33)}
    public static var x99CC66: ColorProtocol {return Color.hex(red: .x99, green: .xCC, blue: .x66)}
    public static var x99CC99: ColorProtocol {return Color.hex(red: .x99, green: .xCC, blue: .x99)}
    public static var x99CCCC: ColorProtocol {return Color.hex(red: .x99, green: .xCC, blue: .xCC)}
    public static var x99CCFF: ColorProtocol {return Color.hex(red: .x99, green: .xCC, blue: .xFF)}
    public static var x99FF00: ColorProtocol {return Color.hex(red: .x99, green: .xFF, blue: .x00)}
    public static var x99FF33: ColorProtocol {return Color.hex(red: .x99, green: .xFF, blue: .x33)}
    public static var x99FF66: ColorProtocol {return Color.hex(red: .x99, green: .xFF, blue: .x66)}
    public static var x99FF99: ColorProtocol {return Color.hex(red: .x99, green: .xFF, blue: .x99)}
    public static var x99FFCC: ColorProtocol {return Color.hex(red: .x99, green: .xFF, blue: .xCC)}
    public static var x99FFFF: ColorProtocol {return Color.hex(red: .x99, green: .xFF, blue: .xFF)}
    public static var xCC0000: ColorProtocol {return Color.hex(red: .xCC, green: .x00, blue: .x00)}
    public static var xCC0033: ColorProtocol {return Color.hex(red: .xCC, green: .x00, blue: .x33)}
    public static var xCC0066: ColorProtocol {return Color.hex(red: .xCC, green: .x00, blue: .x66)}
    public static var xCC0099: ColorProtocol {return Color.hex(red: .xCC, green: .x00, blue: .x99)}
    public static var xCC00CC: ColorProtocol {return Color.hex(red: .xCC, green: .x00, blue: .xCC)}
    public static var xCC00FF: ColorProtocol {return Color.hex(red: .xCC, green: .x00, blue: .xFF)}
    public static var xCC3300: ColorProtocol {return Color.hex(red: .xCC, green: .x33, blue: .x00)}
    public static var xCC3333: ColorProtocol {return Color.hex(red: .xCC, green: .x33, blue: .x33)}
    public static var xCC3366: ColorProtocol {return Color.hex(red: .xCC, green: .x33, blue: .x66)}
    public static var xCC3399: ColorProtocol {return Color.hex(red: .xCC, green: .x33, blue: .x99)}
    public static var xCC33CC: ColorProtocol {return Color.hex(red: .xCC, green: .x33, blue: .xCC)}
    public static var xCC33FF: ColorProtocol {return Color.hex(red: .xCC, green: .x33, blue: .xFF)}
    public static var xCC6600: ColorProtocol {return Color.hex(red: .xCC, green: .x66, blue: .x00)}
    public static var xCC6633: ColorProtocol {return Color.hex(red: .xCC, green: .x66, blue: .x33)}
    public static var xCC6666: ColorProtocol {return Color.hex(red: .xCC, green: .x66, blue: .x66)}
    public static var xCC6699: ColorProtocol {return Color.hex(red: .xCC, green: .x66, blue: .x99)}
    public static var xCC66CC: ColorProtocol {return Color.hex(red: .xCC, green: .x66, blue: .xCC)}
    public static var xCC66FF: ColorProtocol {return Color.hex(red: .xCC, green: .x66, blue: .xFF)}
    public static var xCC9900: ColorProtocol {return Color.hex(red: .xCC, green: .x99, blue: .x00)}
    public static var xCC9933: ColorProtocol {return Color.hex(red: .xCC, green: .x99, blue: .x33)}
    public static var xCC9966: ColorProtocol {return Color.hex(red: .xCC, green: .x99, blue: .x66)}
    public static var xCC9999: ColorProtocol {return Color.hex(red: .xCC, green: .x99, blue: .x99)}
    public static var xCC99CC: ColorProtocol {return Color.hex(red: .xCC, green: .x99, blue: .xCC)}
    public static var xCC99FF: ColorProtocol {return Color.hex(red: .xCC, green: .x99, blue: .xFF)}
    public static var xCCCC00: ColorProtocol {return Color.hex(red: .xCC, green: .xCC, blue: .x00)}
    public static var xCCCC33: ColorProtocol {return Color.hex(red: .xCC, green: .xCC, blue: .x33)}
    public static var xCCCC66: ColorProtocol {return Color.hex(red: .xCC, green: .xCC, blue: .x66)}
    public static var xCCCC99: ColorProtocol {return Color.hex(red: .xCC, green: .xCC, blue: .x99)}
    public static var xCCCCCC: ColorProtocol {return Color.hex(red: .xCC, green: .xCC, blue: .xCC)}
    public static var xCCCCFF: ColorProtocol {return Color.hex(red: .xCC, green: .xCC, blue: .xFF)}
    public static var xCCFF00: ColorProtocol {return Color.hex(red: .xCC, green: .xFF, blue: .x00)}
    public static var xCCFF33: ColorProtocol {return Color.hex(red: .xCC, green: .xFF, blue: .x33)}
    public static var xCCFF66: ColorProtocol {return Color.hex(red: .xCC, green: .xFF, blue: .x66)}
    public static var xCCFF99: ColorProtocol {return Color.hex(red: .xCC, green: .xFF, blue: .x99)}
    public static var xCCFFCC: ColorProtocol {return Color.hex(red: .xCC, green: .xFF, blue: .xCC)}
    public static var xCCFFFF: ColorProtocol {return Color.hex(red: .xCC, green: .xFF, blue: .xFF)}
    public static var xFF0000: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .x00)}
    public static var xFF0033: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .x33)}
    public static var xFF0066: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .x66)}
    public static var xFF0099: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .x99)}
    public static var xFF00CC: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .xCC)}
    public static var xFF00FF: ColorProtocol {return Color.hex(red: .xFF, green: .x00, blue: .xFF)}
    public static var xFF3300: ColorProtocol {return Color.hex(red: .xFF, green: .x33, blue: .x00)}
    public static var xFF3333: ColorProtocol {return Color.hex(red: .xFF, green: .x33, blue: .x33)}
    public static var xFF3366: ColorProtocol {return Color.hex(red: .xFF, green: .x33, blue: .x66)}
    public static var xFF3399: ColorProtocol {return Color.hex(red: .xFF, green: .x33, blue: .x99)}
    public static var xFF33CC: ColorProtocol {return Color.hex(red: .xFF, green: .x33, blue: .xCC)}
    public static var xFF33FF: ColorProtocol {return Color.hex(red: .xFF, green: .x33, blue: .xFF)}
    public static var xFF6600: ColorProtocol {return Color.hex(red: .xFF, green: .x66, blue: .x00)}
    public static var xFF6633: ColorProtocol {return Color.hex(red: .xFF, green: .x66, blue: .x33)}
    public static var xFF6666: ColorProtocol {return Color.hex(red: .xFF, green: .x66, blue: .x66)}
    public static var xFF6699: ColorProtocol {return Color.hex(red: .xFF, green: .x66, blue: .x99)}
    public static var xFF66CC: ColorProtocol {return Color.hex(red: .xFF, green: .x66, blue: .xCC)}
    public static var xFF66FF: ColorProtocol {return Color.hex(red: .xFF, green: .x66, blue: .xFF)}
    public static var xFF9900: ColorProtocol {return Color.hex(red: .xFF, green: .x99, blue: .x00)}
    public static var xFF9933: ColorProtocol {return Color.hex(red: .xFF, green: .x99, blue: .x33)}
    public static var xFF9966: ColorProtocol {return Color.hex(red: .xFF, green: .x99, blue: .x66)}
    public static var xFF9999: ColorProtocol {return Color.hex(red: .xFF, green: .x99, blue: .x99)}
    public static var xFF99CC: ColorProtocol {return Color.hex(red: .xFF, green: .x99, blue: .xCC)}
    public static var xFF99FF: ColorProtocol {return Color.hex(red: .xFF, green: .x99, blue: .xFF)}
    public static var xFFCC00: ColorProtocol {return Color.hex(red: .xFF, green: .xCC, blue: .x00)}
    public static var xFFCC33: ColorProtocol {return Color.hex(red: .xFF, green: .xCC, blue: .x33)}
    public static var xFFCC66: ColorProtocol {return Color.hex(red: .xFF, green: .xCC, blue: .x66)}
    public static var xFFCC99: ColorProtocol {return Color.hex(red: .xFF, green: .xCC, blue: .x99)}
    public static var xFFCCCC: ColorProtocol {return Color.hex(red: .xFF, green: .xCC, blue: .xCC)}
    public static var xFFCCFF: ColorProtocol {return Color.hex(red: .xFF, green: .xCC, blue: .xFF)}
    public static var xFFFF00: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .x00)}
    public static var xFFFF33: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .x33)}
    public static var xFFFF66: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .x66)}
    public static var xFFFF99: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .x99)}
    public static var xFFFFCC: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .xCC)}
    public static var xFFFFFF: ColorProtocol {return Color.hex(red: .xFF, green: .xFF, blue: .xFF)}
}
